# Generated by Django 3.0.10 on 2020-10-12 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=120)),
                ('show_homepage', models.BooleanField()),
                ('category_image', models.ImageField(upload_to='category')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=70)),
                ('product_price', models.IntegerField()),
                ('product_image', models.ImageField(upload_to='product')),
                ('is_bpom', models.BooleanField(default=False)),
                ('is_sibaweh', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenant_name', models.CharField(max_length=70)),
                ('tenant_address', models.TextField()),
                ('tenant_owner', models.CharField(max_length=100)),
                ('tenant_image', models.ImageField(upload_to='tenant')),
            ],
        ),
        migrations.CreateModel(
            name='user_client',
            fields=[
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=35)),
                ('address', models.TextField()),
                ('kecamatan', models.CharField(max_length=50)),
                ('kabupaten', models.CharField(max_length=50)),
                ('post_code', models.IntegerField()),
                ('phone', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=140)),
                ('is_login', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='product_check_halal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halal', models.CharField(blank=True, choices=[(None, '-'), ('bpom', 'BPOM'), ('sibaweh', 'SIBAWEH')], default=None, max_length=10)),
                ('no_halal', models.CharField(max_length=128)),
                ('date_accepted', models.DateField(blank=True, default=None)),
                ('date_expired', models.DateField(blank=True, default=None)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
    ]
