# Generated by Django 3.0.10 on 2020-10-07 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bpom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='is_sibaweh',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='product_check_halal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('halal', models.CharField(blank=True, choices=[(None, '-'), ('bpom', 'BPOM'), ('sibaweh', 'SIBAWEH')], default=None, max_length=10)),
                ('no_halal', models.CharField(max_length=128)),
                ('tgl_halal', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
            ],
        ),
    ]
