# Generated by Django 3.0.10 on 2020-09-30 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id_category',
            new_name='category_id',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name_category',
            new_name='category_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='product_price',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='address_tenant',
            new_name='tenant_address',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='id_tenant',
            new_name='tenant_id',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='name_tenant',
            new_name='tenant_name',
        ),
        migrations.RenameField(
            model_name='tenant',
            old_name='owner_tenant',
            new_name='tenant_owner',
        ),
    ]
