# Generated by Django 3.0.10 on 2020-10-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201007_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_check_halal',
            name='tgl_halal',
        ),
        migrations.AddField(
            model_name='product_check_halal',
            name='date_accepted',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AddField(
            model_name='product_check_halal',
            name='date_expired',
            field=models.DateField(blank=True, default=None),
        ),
    ]
