# Generated by Django 3.0.10 on 2020-10-14 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201014_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='promo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('name', models.TextField()),
                ('image', models.ImageField(upload_to='promo')),
                ('url', models.CharField(max_length=160)),
                ('position', models.IntegerField()),
                ('tenant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='api.tenant')),
            ],
        ),
    ]
