# Generated by Django 3.0.10 on 2020-10-14 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promo',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.tenant'),
        ),
    ]
