# Generated by Django 3.0.10 on 2020-10-12 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201012_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='api.order'),
        ),
    ]
