# Generated by Django 3.0.10 on 2020-11-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_product_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_collections', to='api.category'),
        ),
        migrations.AlterField(
            model_name='product_category',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_collections', to='api.product'),
        ),
    ]
