# Generated by Django 3.0.10 on 2020-11-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20201102_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_category',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
