# Generated by Django 3.0.10 on 2020-11-02 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_product_category_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='note',
        ),
    ]
