# Generated by Django 3.0.10 on 2020-11-03 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_product_product_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='point_demand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='point_favourite',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookmark_date', models.DateField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
