# Generated by Django 3.0.10 on 2020-11-07 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_paycod_paycod_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycod_attachment',
            name='paycod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='api.paycod'),
        ),
    ]
