# Generated by Django 3.0.10 on 2020-12-20 03:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20201107_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment_status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_time', models.DateField(default=django.utils.timezone.now)),
                ('transaction_status', models.CharField(max_length=30)),
                ('payment_type', models.CharField(max_length=120)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
