# Generated by Django 3.0.10 on 2021-01-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210104_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_status',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ostatus', to='api.order'),
        ),
    ]
