# Generated by Django 3.0.10 on 2021-01-04 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20210104_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.IntegerField(default=1),
        ),
    ]
