# Generated by Django 3.0.10 on 2021-01-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_product_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='tenant_city_code',
            field=models.IntegerField(default=0),
        ),
    ]
